### ISSUE TITLE
--restore crashes with ValueError

### ISSUE THREAD

**Issue by WhyNotHugo** [jleclanche/python-bna#11]
Attempting to restore crashes:

```pytb
$ bna --restore EU123412341234 12345678
Traceback (most recent call last):
  File "/home/hugo/.local/share/virtualenvs/tmp/bin/bna", line 313, in <module>
    exit(main())
  File "/home/hugo/.local/share/virtualenvs/tmp/bin/bna", line 309, in main
    return authenticator.run()
  File "/home/hugo/.local/share/virtualenvs/tmp/bin/bna", line 251, in run
    serial, secret = self.restore_serial(*self.args.restore)
  File "/home/hugo/.local/share/virtualenvs/tmp/bin/bna", line 132, in restore_serial
    secret = bna.restore(serial, code)
  File "/home/hugo/.local/share/virtualenvs/tmp/lib/python3.5/site-packages/bna.py", line 224, in restore
    raise ValueError("invalid restore code (should be 10 bytes): %r" % (code))
ValueError: invalid restore code (should be 10 bytes): '12345678'
```

Including the dashes from the serial seems to make no difference:

```pytb
$ bna --restore EU-1234-1234-1234 12345678
Traceback (most recent call last):
  File "/home/hugo/.local/share/virtualenvs/tmp/bin/bna", line 313, in <module>
    exit(main())
  File "/home/hugo/.local/share/virtualenvs/tmp/bin/bna", line 309, in main
    return authenticator.run()
  File "/home/hugo/.local/share/virtualenvs/tmp/bin/bna", line 251, in run
    serial, secret = self.restore_serial(*self.args.restore)
  File "/home/hugo/.local/share/virtualenvs/tmp/bin/bna", line 132, in restore_serial
    secret = bna.restore(serial, code)
  File "/home/hugo/.local/share/virtualenvs/tmp/lib/python3.5/site-packages/bna.py", line 224, in restore
    raise ValueError("invalid restore code (should be 10 bytes): %r" % (code))
ValueError: invalid restore code (should be 10 bytes): '12345678'
```
Relevant information:

```
$ python --version
Python 3.5.2
$ pip freeze
bna==4.1.0
```

I tried installing via pip, or the latest from master, and always got the same result.

**Comment by jleclanche** [comment]
Hmm, I haven't touched the restore code stuff in a long time. I think the way it's done is different now.

I'd love a PR. I'll try to look into it otherwise.

**Comment by WhyNotHugo** [comment]
Thanks!

**Comment by jleclanche** [comment]
Let me know if you still encounter the issue, I haven't been able to reproduce it but I saw that this fixes at least one instance of that crash.
