### ISSUE TITLE
return 500 when use restore function. 

### ISSUE THREAD

**Issue by uavg** [jleclanche/python-bna#18]
hi, when i try to restore my token with bna, it show me below warning. is my operation isn't correct?
```
 bna restore serial code.
```
the error is here;
```
Traceback (most recent call last):
  File "/usr/local/bin/bna", line 4, in <module>
    __import__('pkg_resources').run_script('bna==4.1.0', 'bna')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 658, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1445, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python3.6/dist-packages/bna-4.1.0-py3.6.egg/EGG-INFO/scripts/bna", line 281, in <module>
  File "/usr/lib/python3/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/bna-4.1.0-py3.6.egg/EGG-INFO/scripts/bna", line 225, in restore
  File "/usr/local/lib/python3.6/dist-packages/bna-4.1.0-py3.6.egg/bna/http.py", line 111, in restore
  File "/usr/local/lib/python3.6/dist-packages/bna-4.1.0-py3.6.egg/bna/http.py", line 127, in validate_paper_restore
  File "/usr/local/lib/python3.6/dist-packages/bna-4.1.0-py3.6.egg/bna/http.py", line 31, in get_server_response
bna.http.HTTPError: mobile-service.blizzard.com returned status 500
```

**Comment by Jimmy-Z** [comment]
I guess you're using a CN- serial?

https://gist.github.com/Jimmy-Z/184acceecbd5f435281d86f25ce97dec

**Comment by jleclanche** [comment]
@Jimmy-Z Do you want to submit a PR?

**Comment by Jimmy-Z** [comment]
To be honest I feel uncomfortable working with pip packages, and those missing bits comes from winauth anyway.
