### ISSUE TITLE
cn account can't work

### ISSUE THREAD

**Issue by Wszl** [jleclanche/python-bna#27]
this is logs

```pytb
 Traceback (most recent call last):
  File "/usr/local/bin/bna", line 4, in <module>
    __import__('pkg_resources').run_script('bna==5.0.0', 'bna')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1453, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python3.7/dist-packages/bna-5.0.0-py3.7.egg/EGG-INFO/scripts/bna", line 281, in <module>
  File "/home/wszl/.local/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/wszl/.local/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/wszl/.local/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/wszl/.local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/wszl/.local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/wszl/.local/lib/python3.7/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/bna-5.0.0-py3.7.egg/EGG-INFO/scripts/bna", line 225, in restore
  File "/usr/local/lib/python3.7/dist-packages/bna-5.0.0-py3.7.egg/bna/http.py", line 125, in restore
  File "/usr/local/lib/python3.7/dist-packages/bna-5.0.0-py3.7.egg/bna/http.py", line 46, in initiate_paper_restore
  File "/usr/local/lib/python3.7/dist-packages/bna-5.0.0-py3.7.egg/bna/http.py", line 32, in post
bna.http.HTTPError: mobile-service.battlenet.com.cn returned status 502
```
please help me

**Comment by Wszl** [comment]
i solve this problem by winauth

**Comment by jleclanche** [comment]
@Wszl Please stop closing this unless the isssue is fixed in bna itself.
